# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_olx'),
    ]

    operations = [
        migrations.AddField(
            model_name='domria',
            name='counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='olx',
            name='counts',
            field=models.IntegerField(default=0),
        ),
    ]
