# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190416_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='domria',
            name='price',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='olx',
            name='price',
            field=models.CharField(default='', max_length=255),
        ),
    ]
