# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190417_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='domria',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='olx',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
